# Example docker-compose file with several connected links

version: '3'

services:
  webapp1:
    container_name: webapp1
    image: nginx
    networks:
      - frontend
      - backend
    labels:
      - "com.example.description=Web Application 1"
    ports:
      - "8081:80"
    restart: always

  webapp2:
    container_name: webapp2
    image: nginx
    networks:
      - frontend
      - backend
    labels:
      - "com.example.description=Web Application 2"
    ports:
      - "8082:80"
    restart: always

  database1:
    container_name: database1
    image: postgres
    networks:
      - backend
      - database
    environment:
      POSTGRES_DB: mydb1
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    restart: always

  database2:
    container_name: database2
    image: postgres
    networks:
      - backend
      - database
    environment:
      POSTGRES_DB: mydb2
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
    restart: always

  worker1:
    container_name: worker1
    image: busybox
    networks:
      - backend
      - worker
    command: sleep 3600
    restart: always

  worker2:
    container_name: worker2
    image: busybox
    networks:
      - backend
      - worker
    command: sleep 3600
    restart: always

  monitoring:
    container_name: monitoring
    image: prom/prometheus
    networks:
      - frontend
      - backend
      - monitoring
      - logging
      - cache
    restart: always

  logging:
    container_name: logging
    image: fluentd
    networks:
      - backend
      - logging
      - monitoring
      - cache
    restart: always

  cache:
    container_name: cache
    image: redis
    networks:
      - backend
      - cache
    restart: always

networks:
  frontend:
  backend:
  database:
  worker:
  monitoring:
  logging:
  cache:
