version: "3.8"

services:
  dcDeployControl:
    image: grebtsew/dcdc
    container_name: dcDeployControl
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./${PROJECT_PATH}:/docker # arbitrary docker-compose project
      - ./dcdc_logs:/app/frontend/logs # optionally: volume all system logs
      - /var/run/docker.sock:/var/run/docker.sock # gain docker control access
